
==  Key elements involved in the mapping process
This section provides descriptions and references to the key elements (concepts or resources) that are involved in either the creation of mappings or the mapping process itself.

The purpose of the mapping process is to generate a *mapping table* (described in the conceptual mapping artefact section) that can be processed by the automated workflow of the
//https://github.com/OP-TED/ted-rdf-conversion-pipeline
TED-ODS system. The mapping table is used to convert the TED XML input data into an RDF graph (the output of the mapping) that conforms with the eProcurement Ontology. The mapping table is encoded as a spreadsheet containing multiple worksheets.
//, whose structure is described elsewhere.


=== Notices to be mapped

The inputs for the transformation process are *XML files* that contain TED notice data. These data are structured according to the https://simap.ted.europa.eu/web/simap/standard-forms-for-public-procurement[Standard Forms]  published by the European Commission. There are 23 standard forms defined (numbered 1-8, 12-25, T1 and T2), whose PDF versions can be found here: https://simap.ted.europa.eu/standard-forms-for-public-procurement[https://simap.ted.europa.eu/standard-forms-for-public-procurement].

The XML files must conform to the official Publication Schema.
//TED XML format defined by https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tedschemas[TED XML Schema] (XSD).

Over time, different schema have been developed and there is a significant amount of XML data published that conform to the historical versions. The latest XML notices conform to https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tedschemas[version R2.0.9.S05] of the schema.

=== Contributing Resources

To create these mappings a number of resources produced by earlier or concurrent TED projects were used. The following table contains some of these with short descriptions and links to where the resources can be found.

|===
|*Resource Name*|*Description*
|The e-Procurement Ontology| https://docs.ted.europa.eu/EPO/latest/index.html[The e-Procurement Ontology]
|TED_EXPORT.xsd|The XML Schema defined for the TED XML Notices. Download and extract the versions R2.0.9 and R2.0.8 of the TED XML schema from the links named _Reception: TED eSenders XML schema_ on this page: https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tedschemas[link]
|TED forms PDFs|PDF files representing the physical forms that are to be completed with the relevant data according to each notice. https://simap.ted.europa.eu/standard-forms-for-public-procurement[link]
|Deloitte & OP - TED_XML_Mapping|Excel spreadsheets that map elements (fields, sections, etc.) found in the Standard Forms to elements in the eForms. These tables provide the full list of elements and also XPaths to identify the corresponding information TED-XML files.
|Ontology_eForms_NEW_Mapping_New Regulation|
|Mappings by Everis|Just for reference. Various parts might be out of date.
|Test data set by Everis|A set of approx. 300 XML files (6 batches of about 50 files each, for the forms F02, F03, F05, F06, F24 and F25)
|RDF results by Everis|Just for reference. Various parts might be out of date.
|XML Data analysis|Contains various tables, each summarising certain aspects  (e.g. XML elements related to certain fields in the form) of the data extracted from test notice files.
//https://docs.google.com/spreadsheets/d/1EoHUDDjvx62wXa-LKnDkvolN6dVIeZ_rgm3nNZ91gQo[link]
|XML Elements to Vocabulary Mapping|
|TED Mappings to ePO terms|
//https://github.com/OP-TED/ePO/tree/master/analysis_and_design/ted_mappings[link]
|conventions_report.html|
//Overview of ePO Terms generated from the UML model. https://github.com/OP-TED/ePO/blob/feature/model-refactoring/analysis_and_design/transformation_output/owl_ontology/conventions_report[conventions_report] (to be checked out and open in a browser)
|===


=== Transformation output

The output of the XML notice transformation is an *RDF graph* instantiating the https://docs.ted.europa.eu/EPO/latest/index.html[eProcurement Ontology], containing a number of RDF triples where the subjects, predicates and objects of the triples are either:

* *unique Internationalized Resource Identifiers (IRIs)* that identify either the notice or different components of a notice. These IRIs (or sometimes blank nodes) are used in multiple triples as subjects OR objects to build an *RDF graph*;
* *IRIs* representing *controlled vocabulary terms* or *entities in the ePO ontology*;
* *Literals* representing numbers, boolean values, or strings. The string values are often encoded as multilingual strings of type +rdf:langString+., to facilitate the representation of textual values in multiple European languages.

=== Mapping files produced

The key element enabling transformation automation is the mapping files: *conceptual* and *technical* mappings that are developed according to the mapping creation methodology.

The mapping rules are organised in mapping suites, described in the xref:mapping_suite/mapping-suite-structure.adoc[Mapping Suite Structure].


