[#_technical-mapping-modularisation-chapter]
=== Create RML Rules Modules
Forms tend to have similar or identical sections i.e., represent the same information. For example form F03 and F06 have the same section 1, which is the information about the contract authority.

To remove the need to write transformation rules twice (for section 1 of F03 and section 1 of F06), a module system has been set up which consists of writing transformation rules that are reusable by several forms. This has the following advantages:

* Not needing to rewrite the same rules several times for different forms (avoiding duplication of rules).

* When updating the ePO ontology, the modification will only need to be updated once and will then be passed to all the affected forms.


As explained in the
// xref:mapping_suite/toolchain.adoc#_mapping_creation_method[
//
technical mapping creation section, a TripleMap represents a mapping of an XML element and its content with one class in the ontology, and a set of its predicates objects. To have a module that can be reused on many forms, only the predicates objects of a TripleMap are defined in the module files. The logical sources and subjects map, needed in every TripleMap object, are described separately in the main file as they contain information specific to every form, making these parts of the TripleMap object non-reusable. For example a module that contain an organisation looked like that:

----
<#OrganisationMapping> a rr:TriplesMap ;
	rr:predicateObjectMap
		[
		rr:predicate epo:hasName ;
		rr:objectMap
				[
					rml:reference "OFFICIALNAME"
				]
		] ;

----

This module is extended in the main file of F03 by adding the logicalSource and the SubjectMap in this way:


----
<#OrganisationMapping> a rr:TriplesMap ;
	rml:logicalSource
		[
			rml:source "source.xml" ;
			rml:referenceFormulation ql:XPath
			rml:iterator "/TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/ADDRESS_CONTRACTING_BODY" ;

		] ;
	rr:subjectMap
		[
			rr:template
				"http://data.europa.eu/a4g/resource/Organisation/uuid_generation_function ;
			rr:class epo:Organisation

		] ;
----

The modules are stored in the ted-rdf-mapping project in the `src/mappings` folder.
Five modules that represent the five sections of F03 and part of F06/F25, and one for Annex D1, which is part of F03 are covered. These are:

* s1_contracting_authority.rml.ttl
* s2_object.rml.ttl
* s4_procedure.rml.ttl
* s5_award_of_contract.rml.ttl
* s6_complementary_information.rml.ttl
* annex_d1.rml.ttl

The project contains one `src/mappings` folder containing all the modules files and one "main" entry point mapping file for each form package. Here is a representation:

----
/ted-rdf-mapping
	/XXX
	/mappings
		/package_F03
			/transformation
				XXXX
				/mappings
					...
					technical_mapping_F03.rml.ttl
		/package_FXX
			/transformation
				XXXX
				/mappings
					...
					technical_mapping_FXX.rml.ttl
	/src
		/mappings
			annex_d1.rml.ttl
			s1_contracting_authority.rml.ttl
			s2_object.rml.ttl
			s4_procedure.rml.ttl
			s5_award_of_contract.rml.ttl
			s6_complementary_information.rml.ttl
			technical_mapping_F03.rml.ttl
			technical_mapping_FXX.rml.ttl
----


