:doctitle: Mapping Suites
:doccode: ODS-ROOT-09
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2023


To understand the Mapping Suite Documentation, it would be beneficial to have some of the following:

Knowledge of Semantic Web Technologies:: A good understanding of Semantic Web concepts and technologies is crucial. This includes knowledge of RDF triples, ontologies, and linked data principles.

Understanding of RDF, RML and SPARQL:: Familiarity with RDF (Resource Description Framework) and the RML (the RDF Mapping Language) is important, while experience with SPARQL (SPARQL Protocol and RDF Query Language) is highly beneficial. The TED Open Data Service provides data in RDF format and utilises SPARQL for querying.

Understanding of EU Procurement Data and Familiarity with eProcurement Ontology:: If your goal is to understand how the mappings are used to transform specific types of EU procurement data, such as contract notices or award notices, it's important to have a basic understanding of these concepts, and the https://docs.ted.europa.eu/EPO/latest/index.html[eProcurement Ontology].

////
- [[gloss:cm]] *Conceptual Mapping*, often abbreviated as *CM*, is an abstract level mapping of XPaths in the input data to those ePO classes that need to be instantiated and properties are used to link the instances in the output RDF graph

- [[gloss:epo]] *eProcurement Ontology (ePO)* is an ontology that defines the concepts and relations that are needed to fully describe the eProcurement domain of the EU. For more information check out the https://docs.ted.europa.eu/EPO/latest/index.html[eProcurement Ontology Documentation].

- [[gloss:eForms]] *eForms* is the notification standard for public procurement procedures in the EU. For more information on this, see the https://docs.ted.europa.eu/eforms/latest/index.html[eForms SDK documentation]

- [[gloss:form]] *Form* - To enable the publishing of the EU public procurement data in the Official Journal, the European Commission has created standard forms aligned with each of the EU legal bases in place for publishing this data, namely: the *TED schema forms* set out in Regulation (EU) 2015/1986, and the *eForms* set out in Regulation (EU) 2019/1780. In this documentation the term "form", if not otherwise specified, will refer to xref:gloss:stdForm[Standard Form]

- [[gloss:mapping_package]] *Mapping package* - see xref:gloss:ms_package[*Mapping suite package*]

- [[gloss:ms_package]] *Mapping suite package* is a collection of files, organized in a folder hierarchy, that fully specify how the mapping of a certain category of notices (e.g. notices created according to specific XSD version of a specific TED Standard form) is being converted to RDF. This collection includes the conceptual mapping (CM), the technical mappings (realised as RML files), additional resources that are needed to complement the mappings, some xref:gloss:test_data[test data], the generated output from the test data, the validation queries and validation reports generated based on the mappings and on the generated RDF output. For more details please see the xref:mapping:mapping-suite-structure.adoc[Mapping Suite Structure].

- [[gloss:notice]] *Notice*, short for *public procurement notice*, refers to a procurement notice published on xref:gloss:ted[TED]. To explore some of these notices please visit: https://ted.europa.eu/TED/

- [[gloss:package]] *Package* - often used as a short name for xref:gloss:ms_package[*Mapping suite package*]

- [[gloss:rml]] *RDF Mapping Language (RML)* is a generic mapping language defined to express customized mapping rules from heterogeneous data structures and serializations to the RDF data model. RML is defined as a superset of the W3C-standardized mapping language [R2RML] and follows exactly the same syntax as https://www.w3.org/TR/r2rml/[R2RML]; therefore, RML mappings are themselves RDF graphs. For more information on RML, please see https://rml.io/specs/rml/.

- *Standard Form* - see xref:gloss:stdForm[TED Standard Form]

- [[gloss:tm]] *Technical Mapping*, often abbreviated as *TM*, is set of RML rules that can be used to transform notice XML, into its which are split in multiple reusable modules that can be combined to represent a full RML

- [[gloss:ted]] *Tenders Electronic Daily (TED)*, is an online portal that publishes hundreds of thousands of public procurement notices per year.  A cornerstone of European public procurement, TED helps economic operators find business opportunities from around the EU. For more information see: https://ted.europa.eu/TED/main/HomePage.do

- [[gloss:stdForm]] *TED Standard Form* or *TED schema forms* refers to the "TED Standard forms for public procurement" described here: https://simap.ted.europa.eu/en_GB/web/simap/standard-forms-for-public-procurement. These forms are numbered F01-F08, F12-F25 and T01-T02, and must conform to a specific version the xref:gloss:xsd[TED XML Schema].

- [[gloss:xsd]] *TED XML schema* refers to the XML schema (XSD) specified for validating the notices that are published according to the Regulation (EU) 2015/1986. For a full documentation of the various XSD schemas, and their versions, please check out:
https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tedschemas

- [[gloss:test_data]] *Test data* - a carefully selected, representative sample of real notices published on TED, which, together, cover all the different XPaths that can appear in the entire set of Public Procurement Data (PPD) of a certain type (i.e. created based on a specific Form, specific XSD version), and published in a certain date range. For more detailed documentation, please check out the xref:mapping_suite/preparing-test-data.adoc[] section

- [[gloss:xpath]] *XPath* - the XML Path Language (XPath) Version 1.0. See https://www.w3.org/TR/xpath-10/

////

// include::../glossary.adoc[]

== Mapping Suite Contents
Transformation rules and other artefacts used for the mapping of Standard Forms and eForms for the TED Open Data Service are organised in the ted-rdf-mapping repository.
The repository structure and folder descriptions are shown below.  The base of the folder path is https://github.com/OP-TED/ted-rdf-mapping/tree/main/.  However, if the reader wishes to view a specific release, then the path is adapted by replacing main by the given release. For example, if release 2.1.1-rc.1 is required, the path should be amended to https://github.com/OP-TED/ted-rdf-mapping/tree/2.1.1-rc.1


=== Upper Level folders of the GitHub Repository

This section describes the upper level of the GitHub repository, the next section describes the lower levels of the GitHub repository where the more granular artefacts can be found. The aim of this section is to give the reader an overview of the repository structure.

[cols="1,1,2"]
|===
|Folder|Subfolders |Description

|/docs
|/antora
|Contains the documentation for the ted-rdf mapping

|https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings[/mappings]
a|https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03[/package_F03]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F06[/package_F06]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F13[/package_F13]
//https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F20[/package_F20]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F21[/package_F21]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F23[/package_F22]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F23[/package_F23]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F25[/package_F25]


NB: the example provided here is for Standard Form F03 but can be applied in the same way for the mapping suites for the other forms covered by the mappings.

a|Contains xref:mapping:mapping-suite-structure.adoc[mapping suite packages] organised based on the standard forms numbers. Their name is formed based on the form number (e.g. F03, F06) prefixed with package_ for readability. When the eForms are mapped, the corresponding appropriate organisation will be chosen.

| /mappings continued: subfolders
a|https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_2021[/package_F03/test_data/form_number_F03_2021]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_S01[/package_F03/test_data/form_number_F03_S01]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_S02[/package_F03/test_data/form_number_F03_S02]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_S03[/package_F03/test_data_form_number_F03_S03]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_S04[/package_F03/test_data_form_number_F03_S04]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_S05[/package_F03/test_data_form_number_F03_S05]

NB the example provided here is for Standard Form F03 but can be applied in the same way to the other form package.

a|Contains example notices extracted from the TED website with real data for the forms concerned in this example F03.

The folder ending F03_2021 contain examples from notices published in 2021

The folder ending F03_S01 contains examples from notices published using the xml release R2.0.9.S01.E01

The folder ending F03_S02 contains examples from notices published using the xml release R2.0.9.S02.E01, and so forth whereby the S01 is replaced by either S02, S03, S04 and S05


The latest publication xml can be found at TED schemas - EU Vocabularies - Publications Office of the EU (europa.eu) under Publication Schema the Excel file in the zip file provides the change log between schema.



|https://github.com/OP-TED/ted-rdf-mapping/tree/main/src[/src]
a|https://github.com/OP-TED/ted-rdf-mapping/tree/main/src/mappings[/mappings]

a|Contains the "single source of truth" for the mapping rules across various mapping suite packages. This is necessary because of the modularisation and reuse method adopted in this project. The basic idea is that the mapping rules are organised in modules, and all are stored in the source folder.

Each mapping suite provides in the conceptual mapping workbook the list of modules that be used to compose the complete set of transformation rules of the mapped form number.

|/test_data
a|https://github.com/OP-TED/ted-rdf-mapping/tree/main/test_data/sampling_2014_2022[/sampling_2014_2022]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/test_data/sampling_2021[/sampling_2021]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/test_data/sampling_manual/form_number_F03[/sampling_manual]
a|Covers samples of notices across all form types whether they are covered by the actual mappings covered to date.

The samples are broken down by a mapping to the eForms sub-type:

/sampling_2014_2022 and sampling_2021 cover notices over the respective periods and are generated respectively.

/sample_manual are notices that have been produced manually concerning F03

Test data is also provided in the mapping suite packages that are specific to the mapping suites.

|===


=== The lower level folders of the GitHub Repository

This section provides more detailed information on the content available in the lower levels of the repository:

* Mapping suite package structure

** output

** test-data

** transformation

** validation

* source files

** mappings

** validation



//include::ted-sws-introduction.adoc[Old Introduction]

//include::methodology.adoc[]

//include::toolchain.adoc[]

include::partial$feedback.adoc[]