= Mapping Methodology

The purpose of this guide is to describe a *methodology for creating mapping rules* that transform XML data representing the content of the TED “Standard” Forms, into RDF graphs that conform to the https://github.com/OP-TED/ePO[ePO ontology].

The current mapping methodology relies on resources generated by earlier attempts to create a methodology by e.g., Everis, outcomes of related projects by e.g., by Deloitte e.a., and a number of experts in  the ePO ontology, and Semantic Web technologies in general.

The mappings generated by this methodology are intended for use in
//https://docs.ted.europa.eu/rdf-conversion/_attachments/ted-sws-architecture/index.html?goto=1:1:36[
the notice transformation workflow for *all* https://ted.europa.eu/TED/browse/browseByMap.do[Tenders Electronic Daily (TED)] notices conforming to "Standard" forms that are published in the TED XML format, into RDF format, in order to make it available for querying through a SPARQL endpoint.


include::partial$methodology/mapping-lifecycle.adoc[]

include::partial$methodology/key-elements-for-mapping.adoc[]

include::partial$methodology/conceptual-mapping-structure.adoc[]

include::partial$methodology/mapping-creation-method.adoc[]

include::partial$methodology/technical-mapping-modularisation.adoc[]
