:doctitle: Reusing TED Data
:doccode: ODS-REUS-01
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: November 2023


Download of notices in xml format, in daily or monthly packages, can be done from the https://ted.europa.eu/en/[TED Website]. Notices are also available in html, html download, signed pdf,
unsigned pdf, and xml, using direct links.

In addition, the Search API can be used in different modes to query notice data. Click on the links below for more detail on the various download methods.


== Access Methods

* xref:search-api.adoc[Search and retrieve data published on the TED portal (TED search API] +
Download notices via the Search API
* xref:download-direct.adoc[Downloads notices in various formats using direct links] +
Download bulk notice packages using a direct link
* xref:search-api-demo.adoc[Examples using the Search API] +
See some examples of how to use the Search API
* xref:download-xml.adoc[Download XML notices in bulk] +
Bulk downloads in FTP format
* https://data.europa.eu/data/datasets/ted-csv?locale=en[TED subsets in CSV format]
* xref:ftp.adoc[TED schemas archive] +
This page contains the TED schemas archive resources
* xref:calendar.adoc[Download the release calendar[]]

== List of search fields used on the TED Site

A comprehensive list of search fields used on the TED website can be viewed via the link below

* xref:field-list.adoc[Search field list]
