:doctitle: Reusing TED Data
:doccode: ODS-REUS-01
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: November 2023

.Survey: Reusing TED Data documentation
****

We are conducting a survey on how you find the documentation on the *Reusing TED Data* documentation. We would really appreciate you filling in the survey and giving us your feedback.  You can access the survey here:

https://ec.europa.eu/eusurvey/runner/670dc92b-c6ef-94d5-3af0-c54d65b0ad6d[Reusing the TED DATA documentation survey]

Thank-you for your time. Your feedback will help us create documentation that helps you use the data better.
****

Download of notices in xml format, in daily or monthly packages, can be done from the https://ted.europa.eu/en/[TED Website]. Notices are also available in html, html download, signed pdf,
unsigned pdf, and xml, using direct links.

In addition, the Search API can be used in different modes to query notice data. Click on the links below for more detail on the various download methods.


== Access Methods

* xref:download-xml.adoc[XML Downloads] +
Bulk downloads in FTP format
* xref:download-direct.adoc[Direct downloads via html links] +
Download bulk notice packages using a direct link
* xref:search-api.adoc[Downloads via Search API] +
Download notices via the Search API
* xref:search-api-demo.adoc[Examples using the Search API] +
See some examples of how to use the Search API
* xref:ftp.adoc[TED schemas archive] +
This page contains the TED schemas archive resources

== List of search fields used on the TED Site

A comprehensive list of search fields used on the TED website can be viewed via the link below

* xref:field-list.adoc[Search field list]

