:doctitle: Reusing TED XML Data from the TED Website
:doccode: ODS-REUS-01
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: November 2023

.Survey
****
A survey is underway on how helpful you find the *Reusing TED XML Data* documentation. We are really interested in your thoughts and feelings about it, and would appreciate you filling in the survey and telling us.  You can access the survey here:

https://ec.europa.eu/eusurvey/runner/670dc92b-c6ef-94d5-3af0-c54d65b0ad6d[Reusing TED XML DATA: Survey of the Documentation ]

Thank-you for your time. Your feedback will help us create documentation that helps you use the data better.
****

Download of notices in xml format, in daily or monthly packages, can be done from the https://ted.europa.eu/en/[TED Website]. Notices are also available in html, html download, signed pdf,
unsigned pdf, and xml, using direct links.

In addition, the Search API can be used in different modes to query notice data. Click on the links below for more detail on the various download methods.


== Access Methods

* https://ted.europa.eu/en/simap/developers-corner-for-reusers#search-retrieve-data[Download notices via the Search API] +
Search and retrieve data published on the TED portal using the TED search API
* https://ted.europa.eu/en/simap/developers-corner-for-reusers#download-notices-various-formats[Downloads notices in various formats using direct links] +
Download bulk notice packages using a direct link
* https://ted.europa.eu/en/simap/developers-corner-for-reusers#download-xml-notices[Download XML notices in bulk] +
Bulk downloads in FTP format
* https://ted.europa.eu/en/simap/developers-corner-for-reusers#download-release-calendar[Download the release calendar] +
Download the list of the OJS releases per year
* https://data.europa.eu/data/datasets/ted-csv?locale=en[TED subsets in CSV format] +
Download yearly bundles in CSV format
* xref:ftp.adoc[TED schemas archive] +
The TED schemas archive resources


== List of search fields used on the TED Site

A comprehensive list of search fields used on the TED website can be viewed via the link below

* xref:field-list.adoc[Search field list]
