# Who are the winners for a given date?

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX cccev: <http://data.europa.eu/m8g/>
SELECT DISTINCT
?ProcedureNr
?LotNr
?WinnerLegalName
?WinnerCountryCode
?AwardedValue
?AwardedValueCurrency
WHERE {
    VALUES ?NoticePublicationDate {
        "20230921"
    }
    FILTER(LANG(?WinnerLegalName) = 'en')
    ?NoticeId a epo:ResultNotice;
              epo:hasPublicationDate ?NoticePublicationDate;
              epo:refersToLot ?Lot.
    ?Lot a epo:Lot.
    ?LotAwardOutcome epo:describesLot ?Lot;
                     a epo:LotAwardOutcome;
                     epo:comprisesTenderAwardOutcome ?TenderAwardOutcome.
    ?TenderAwardOutcome a epo:TenderAwardOutcome;
                        epo:indicatesAwardOfLotToWinner / epo:playedBy ?Winner.
    ?Winner a org:Organization;
            epo:hasLegalName ?WinnerLegalName .
    OPTIONAL {
        ?Winner cccev:registeredAddress / epo:hasCountryCode ?WinnerCountryCode.
    }
    ?LotAwardOutcome epo:hasAwardedValue ?LotAwardedValue.
    ?LotAwardedValue a epo:MonetaryValue;
                     epo:hasAmountValue ?AwardedValue;
                     epo:hasCurrency ?AwardedValueCurrency.
  OPTIONAL {
          ?Lot epo:hasID / epo:hasIdentifierValue ?LotNr .
  }
  ?Procedure epo:hasProcurementScopeDividedIntoLot ?Lot;
             a epo:Procedure ;
             epo:hasID / epo:hasIdentifierValue ?ProcedureNr .
}