:doctitle: Querying Public procurement Data
:doccode: sws-main-prod-020
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2023

include::starting.adoc[]

== Designing a Query

Generally, you will start a new query process with a specific scenario or context in which a question about EU public procurement is asked. The following steps then follow:

=== Examination of the scenario
* A short investigation into the extent to which the current data offering can satisfy your question
* Understanding data limitations
* Refining the question

=== Identifying the information to be returned
* Using the eProcurement ontology (glossary and conceptual model) to identify the classes and class relationships that can be used to find the information
* Constructing the query

=== Executing the query
* Running the query
* Examining and refining the query results

== The sample applications

Sample applications are provided for you to try out using the following query methods:

* Microsoft Excel
* Python
* R
* The SPARQL EndPoint

You can access these via the menu on the left hand side under "Reusing TED Open Data". 

If you are not a programmer and new to querying RDF data, you can start by using the Excel file provided to paste the sample query into and see the results.

The Excel file contains a macro which connects to the SPARQL EndPoint, submits the query for you, and returns the results back into the spreadsheet. The spreadsheet also contains a sheet with a preformatted results dashboard that you can change as needed.

The next method is submitting a query directly into the SPARQL EndPoint. Here you can choose the desired returned data format from the options, and deal with the formatting of the results as you wish.

The last two query options are using Jupyter Notebook with either R and Python.

Read through the example applications and try them out in your own time. You will soon get an idea of which method suits you best.

include::tips.adoc[]

////
== Prerequisites

To use TED-ODS sample apps, you will need the following:

Understanding of RDF and SPARQL:: Familiarity with RDF (Resource Description Framework) and SPARQL (SPARQL Protocol and RDF Query Language) is crucial. TED-ODS provides data in RDF format and utilizes SPARQL for querying.

Access to a Programming Language:: You should have proficiency in a programming language capable of making HTTP requests and processing data. Common choices include Python or R.

Knowledge of Semantic Web Technologies:: A basic understanding of Semantic Web concepts and technologies is beneficial. This includes knowledge of RDF triples, ontologies, and linked data principles.

Development Environment:: Set up a development environment for your chosen programming language or at least ensure that you have installed MS Excel.

Understanding of EU Procurement Data:: If your goal is to work with specific types of EU procurement data, such as contract notices or award notices, it's important to have a basic understanding of these concepts, and the associated https://docs.ted.europa.eu/EPO/latest/index.html[ontology].

The sample applications can be accessed via the menu on the left.

The sample applications can be accessed via the menu on the left.


== Using MS Excel

* <<SWS:ROOT:sample_app/ms_excel.adoc#, MS Excel Workbook>>

Example of accessing data in a MS Excel workbook.

== SPARQL Query examples

* <<SWS:ROOT:sample_app/sparql_queries.adoc#, SPARQL Query examples>>

Example of accessing data using SPARQL Query examples


== Using Jupyter Notebook

* <<SWS:ROOT:sample_app/jupyter_notebook_python.adoc#, Jupyter Notebook - Python>>

Example of using Python language and to access data.

* <<SWS:ROOT:sample_app/jupyter_notebook_r.adoc#, Jupyter Notebook - R>>

Example of using R language and to access data.
////


include::partial$feedback.adoc[]




