:doctitle: Start querying procurement data using SPARQL
:doccode: ods-main-prod-102
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: July 2024

== How RDF data is queried

RDF data is queried using SPARQL, a query language specifically for querying RDF data. A guide for querying RDF data and constructing a query can be found https://docs.ted.europa.eu/docs-staging/epo-home/guide.html[here]. Once a query is ready, it is pasted into the SPARQL EndPoint's input field and executed.

== Links to online training resources for learning SPARQL

There are many good online resources on SPARQL and constructing SPARQL queries:

 * The guides on the ePO page for learning about RDF and SPARQL can be found in the ePO Docs https://docs.ted.europa.eu/docs-staging/epo-home/guide.html[here]
 * https://www.w3.org/TR/sparql11-query/[W3C]
 * YouTube lectures:
 ** https://www.youtube.com/watch?v=zkr_2HR4Pcs&list=PLakGkiOE3_q8Fq46-TSE-Te1cvx8yLLUF[Linked Data and SPARQL]
 ** https://www.youtube.com/playlist?list=PLoOmvuyo5UAfY6jb46jCpMoqb-dbVewxg[Linked data Engineering]
 * Videos:
 ** https://www.youtube.com/watch?v=FvGndkpa4K0[SPARQL in 11 Minutes]
 ** https://www.youtube.com/watch?v=zteyEk9LADs&t=338s[RDF and OWL]
 * Other web-based training courses on training sites like Udemy.
 * Books from publishers such as O'Reilly, The Dummies Guide to, Morgan Kaufmann, etc.

== Guides for using ePO resources when designing queries

Guides to using resources provided by the eProcurement Ontology to assist in constructing queries can be found https://docs.ted.europa.eu/docs-staging/epo-home/guide.html[here]. These are specific to EU public procurement and will help find the concepts or classes you will use in your queries.

== Procurement Data

Public procurement data available for query comes from notice data. For a short introduction of what data can be found in notices, you can go to the ted.europa.eu website and examine a notice. Any notice can be found by opening the latest issue of the Official Journal Supplement, or by using one of the several ways of searching for notices available on the site: advanced, expert, or browse by subject.

As an aid, you can use these short info sessions on xref:attachment$notice_data/index.html[Notice Data] and xref:attachment$searching_notices/index.html[Searching Notices] to familiarise yourself with notices and how to use the ted.europa.eu search possibilities.

This should give you an overview of what information can be found in a notice.

== Converting Notice Data into RDF format

On the ted.europa.eu website you will soon realise that while servicing buyers and sellers well who wish to buy or supply goods or services, searching for combined data on many notices, or mass notices historically, is not what the site is designed for.

As part of the European Commission's strategy for data reuse and transparency, notice data is converted into RDF format using an automated "pipeline" service.

The data, stored in the "Cellar", the RDF triplestore (database) maintained by the Publications Office, enables anyone to query notice data as Linked Open Data using Cellar's https://publications.europa.eu/webapi/rdf/sparql[SPARQL EndPoint].



//Some tips regarding queries can be found xref:tips.adoc[here].
//=== Flow diagramme of frequently used classes: buyer, seller, value, date, country, business size, cpv codes, lots


//* in WHERE statements: declaring a variable as an epo class
