:doctitle: RDF Queries
:doccode: sws-main-prod-020
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2024

== Designing a Query

Generally, you will start a new query process with a specific scenario or question about EU public procurement. 

=== Examination of the scenario
* A short investigation into how the current data offering can best satisfy your question
* Refining the question

=== Identifying the information to be returned
* Using the eProcurement ontology (glossary and conceptual model) to identify the classes and class relationships that can be used to find the information required
* Constructing the query

=== Deciding which query method to choose
* Pasting the query directly into Cellar's SPARQL EndPoint
* Using Microsoft Excel
* Using Jupyter Notebooks and Python

=== Executing the query
* Running the query
* Examining and refining the query results

== Sample Queries
Sample queries are provided for you to try out using the different query methods. Ways to connect to the data can be found under "Connecting to TED Open Data". 


//include::tips.adoc[]









