:doctitle: RDF Queries
:doccode: sws-main-prod-020
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2024

== Designing a query

Generally, you will start a new query process with a specific scenario or question about EU public procurement in mind. 

=== Examination of the scenario
* Then you will perform a short investigation into how the current data offering can best satisfy your question. This will help you refine your question

=== Identifying the information to be returned
* After you have refined your question, you will use the eProcurement ontology (glossary and conceptual model) to identify the classes and class relationships that can be used to find the information you require and construct your query

=== Deciding which query method to choose
Once you have finalised your query, you will choose which submission method to use:

* Pasting the query directly into Cellar's SPARQL EndPoint
* Using Microsoft Excel
* Using Jupyter Notebooks and Python

=== Executing the query
Then you will run your query before examining and refining the query results

== Sample queries
Sample queries are provided for you to try out using the different query methods. Ways to connect to the data can be found under "Connecting to TED Open Data". 


//include::tips.adoc[]









