:doctitle: RDF Queries
:doccode: sws-main-prod-020
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2024

== Designing a Query

Generally, you will start a new query process with a specific scenario or question about EU public procurement. The following steps then follow.

=== Examination of the scenario
* A short investigation into the extent to which the current data offering can satisfy your question
* Refining the question

=== Identifying the information to be returned
* Using the eProcurement ontology (glossary and conceptual model) to identify the classes and class relationships that can be used to find the information required
* Constructing the query

=== Executing the query
* Running the query
* Examining and refining the query results

== Sample Queries

Sample queries are provided for you to try out using the following query methods:

* Pasting the query directly into Cellar's SPARQL EndPoint
* Microsoft Excel
* Python

Ways to connect to the data can be found under "Connecting to TED Open Data". 


//include::tips.adoc[]









