:doctitle: Querying Public procurement Data
:doccode: sws-main-prod-020
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2023

include::starting.adoc[]

== Designing a Query

Generally, you will start a new query process with a specific scenario or context in which a question about EU public procurement is asked. The following steps then follow:

=== Examination of the scenario
* A short investigation into the extent to which the current data offering can satisfy your question
* Understanding data limitations
* Refining the question

=== Identifying the information to be returned
* Using the eProcurement ontology (glossary and conceptual model) to identify the classes and class relationships that can be used to find the information
* Constructing the query

=== Executing the query
* Running the query
* Examining and refining the query results

== The sample applications

Sample applications are provided for you to try out using the following query methods:

* Pasting the query directly into Cellar's SPARQL EndPoint
* Microsoft Excel
* Python

You can access these via the menu on the left hand side under "Connecting to TED RDF Data". 

If you are not a programmer and new to querying RDF data, you can start by pasting a sample query directly into the SPARQL Endpoint and viewing the results online.

Once the EndPoint has returned the results of the query, you can copy the url of the results page and paste it into Excel via the "Data" -> "from Web" menu functionality, and then save the spreadsheet. This will pull the results from the SPARQL EndPoint directly into Excel, and enable you to refresh the data in the future from Excel, where you can take advantage of Excel's data visualisation capabilities such as graphs or charts. 

The most advanced method of extracting data is by using Python.

Use the resources and sample queries to try out these methods to see which suits you best.

== Community Discussion on GitHub

Get and give tips and advice amongst fellow query creators. The GitHub discussion space is where to find the EU public procurement query community.

//include::tips.adoc[]


include::partial$feedback.adoc[]




