= notice data


== Getting familiar with public rocurement Data

Public procurement data available for query comes from notice data. For a short introduction of what data can be found in notices, you can go to the ted.europa.eu website and examine a notice. Any notice can be found by opening the latest issue of the Official Journal Supplement, or by using one of the several ways of searching for notices available on the site: advanced, expert, or browse by subject.
You can use the TED website, where public buyers submit their calls for tender, to familiarise yourself with the fields or concepts used in notices. The search possibilities on the TED website return data that give you an idea of the format of the data contained in the Cellar triple store. The date returned here is notice-based, and on current activity in EU public procurement tenders, and does not contain all the historical data, but it will give you an idea about the fields available to query. This is XML data before its conversion into RDF.

Bear in mind that the OP is working on converting more types of current notice data into RDF, and adding historical data, so the triple store data available will grow over time. Keep an eye on the data availability page to keep up to date.

As an aid, you can use these short info sessions on xref:ROOT:attachment$/notice_data/index.html[Notice Data] and xref:ROOT:attachment$/searching_notices/index.html[Searching Notices] to familiarise yourself with notices and how to use the ted.europa.eu search options.

This should give you a good idea of the information that can be found in a notice.



