:doctitle: Overview RDF Queries
:doccode: sws-main-prod-020
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2024

== How RDF Data is Queried

=== Designing a Query

Generally, you will start a new query process with a specific scenario or question about EU public procurement. The following steps then follow.

==== Examination of the scenario
* A short investigation into the extent to which the current data offering can satisfy your question
* Understanding data limitations
* Refining the question

==== Identifying the information to be returned
* Using the eProcurement ontology (glossary and conceptual model) to identify the classes and class relationships that can be used to find the information
* Constructing the query

==== Executing the query
* Running the query
* Examining and refining the query results

== The sample applications

Sample queries are provided for you to try out using the following query methods:

* Pasting the query directly into Cellar's SPARQL EndPoint
* Microsoft Excel
* Python

You can learn how to use these methods of connecting to the data via the menu on the left hand side under "Connecting to TED Open Data". 


//include::tips.adoc[]

=== RDF Data

RDF data has a specific format made up of a "semantic triple", explained in more detail in the info session on RDF linked in the online training resources section below. An info session on https://docs.ted.europa.eu/docs-staging/epo-home/_attachments/LOD/index.html[Linked Open Data] is also available. (linked open data is RDF data that is licenced as open i.e., for reuse).

RDF Data is queried using a query language called SPARQL, or .... SPARQL Query Language. RDF data is stored in what is called triples e.g., if the database had a list of people and their phone numbers, the triples would look like this:

Mary - HasNumber - 555-123456 +
Janet - HasNumber - 555-345678 +
John - HasNumber - 555-234567


The data looks a little like a sentence with a subject (Name), predicate (HasNumber) and object (Number).

There are many triples stored in such a database, for Name, there would be the usual personal details categories as well as information specific to that database (music/ sports/ job). Many objects could be associated with John or Janet via different predicates.







