:doctitle: Start querying procurement data using SPARQL
:doccode: ods-main-prod-102
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: July 2024

== How RDF data is queried

RDF data is queried using SPARQL, a query language specifically for querying RDF data. 

Once a query is ready, it is pasted into a SPARQL EndPoint input field and executed.

An EndPoint is a URI connected to a RDF database or triple store that provides access to the data in it. Each triple store has its own EndPoint.

Before you get to the point where you construct a query, there are a few topics worth reading through and getting familiar with such as: 

* Understanding RDF Data
* Writing SPARQL queries
* Connecting to the data

In the left-hand menu there are links to resources to help you get started.

There are also some sample queries that can be accessed via the menu on the left, and a description of the methods ways of running SPARQL queries. The example queries can be copied and pasted, as is, into any of the different query methods.

////
== Converting notice data into RDF format

On the ted.europa.eu website you will soon realise that while servicing buyers and sellers well, who wish to buy or supply goods or services, searching for combined data on many notices, or mass notices historically, is not what the site is designed for.

As part of the European Commission's strategy for data reuse and transparency, notice data is converted into RDF format using an automated "pipeline" service.

The data, stored in the "Cellar", the RDF triple store (database) maintained by the Publications Office, is open to anyone who wishes to query notice data as Linked Open Data using the query methods found in the menu on the left under "Connecting to RDF data".

The section on creating mappings to convert XML data to RDF can also be found in the left-hand menu.

////

