:doctitle: Start querying procurement data using SPARQL
:doccode: ods-main-prod-102
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: July 2024

== EU public procurement data

EU public procurement data is made available for querying in RDF format. This is done by converting notice data in XML to RDF format via a pipeline process that detects the presence of notice data and runs an automated process converting the XML to RDF. The converted data is stored in a public procurement RDF database, also known as a triple store, called the "Cellar".

Anyone, with a little know-how, and with help from the resources provided, can learn to create their own queries, and retrieve data on EU public procurement from Cellar. 

== How RDF data is queried

RDF data is queried using SPARQL, a query language specifically for querying RDF data. 

Once a query is ready, it is pasted into a SPARQL EndPoint and executed.

A SPARQL EndPoint is a URI connected to a RDF triple store, that provides access to the data. Each triple store has its own EndPoint. The EndPoint is presented to the public in the form of a webpage with a field, or textbox, into which a SPARQL query can be pasted. The query results are returned in a table.


Use the resources provided here to: 

* Learn what resources are available to help you start querying public procurement data
* Understand RDF Data
* Write SPARQL queries
* Connect to open public procurement data

In the menu on the left there are links to resources to help you get started.

Sample queries are available as is a description of the various methods ways of running SPARQL queries that you can try out for yourself. The sample queries can be in any of the different query methods.


=== RDF Data

RDF data has a specific format made up of a "semantic triple", explained in more detail in the https://docs.ted.europa.eu/docs-staging/epo-home/_attachments/LOD/index.html[Linked Open Data info session].

RDF Data is queried using a query language called SPARQL (SPARQL Protocol and RDF Query Language). As mentioned before, RDF data is stored in what is called triples - if the database had a list of people and their phone numbers, the triples would look like this:

Mary - HasNumber - 555-123456 +
Janet - HasNumber - 555-345678 +
John - HasNumber - 555-234567


The data look a little like a sentence with a subject (Name), predicate (HasNumber) and object (Number).

There are many triples stored in such a database. For Name, there would be the usual personal details categories as well as information specific to that database (music/ sports/ jobs). Many objects could be associated with John or Janet via different predicates.


////
== Converting notice data into RDF format

On the ted.europa.eu website you will soon realise that while servicing buyers and sellers well, who wish to buy or supply goods or services, searching for combined data on many notices, or mass notices historically, is not what the site is designed for.

As part of the European Commission's strategy for data reuse and transparency, notice data is converted into RDF format using an automated "pipeline" service.

The data, stored in the "Cellar", the RDF triple store (database) maintained by the Publications Office, is open to anyone who wishes to query notice data as Linked Open Data using the query methods found in the menu on the left under "Connecting to RDF data".

The section on creating mappings to convert XML data to RDF can also be found in the left-hand menu.

////

