:doctitle: Tutorials and Resources
:doccode: sws-main-prod-020
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2023

RDF data is queried using SPARQL, a query language specifically for querying RDF data. A short info session on querying RDF data and constructing a query can be found below in the RDF Data section below. 

Once a query is ready, it is pasted into the SPARQL EndPoint's input field and executed.

Before you get to the point where you construct a query, there are a few topics worth reading through and getting familiar with. There are links below to more information or training resources.

There are also some example queries that can be accessed via the menu on the left, which walk you through a few methods of running SPARQL queries. The example queries can be copied and pasted, as is, into any of the different query methods.

== RDF Data

RDF data has a specific format made up of a "semantic triple", explained in more detail in the info session on RDF linked in the online training resources section below. An info session is also available on Linked Open Data https://docs.ted.europa.eu/docs-staging/epo-home/_attachments/LOD/index.html[here], which is linked RDF data that is licenced as open (for reuse).

== Links to online training resources for learning SPARQL

There are many good online resources on SPARQL and constructing SPARQL queries:

 * The info sessions on the ePO page for learning about RDF and SPARQL can be found in the ePO Docs https://docs.ted.europa.eu/docs-staging/epo-home/_attachments/RDF/index.html[here]
 * https://www.w3.org/TR/sparql11-query/[W3C]
 * YouTube lectures:
 ** https://www.youtube.com/watch?v=zkr_2HR4Pcs&list=PLakGkiOE3_q8Fq46-TSE-Te1cvx8yLLUF[Linked Data and SPARQL]
 ** https://www.youtube.com/playlist?list=PLoOmvuyo5UAfY6jb46jCpMoqb-dbVewxg[Linked data Engineering]
 * Videos:
 ** https://www.youtube.com/watch?v=FvGndkpa4K0[SPARQL in 11 Minutes]
 ** https://www.youtube.com/watch?v=zteyEk9LADs&t=338s[RDF and OWL]
 * Other web-based training courses on training sites like Udemy.
 * Books from publishers such as O'Reilly, The Dummies Guide to, Morgan Kaufmann, etc.

== Guides for using ePO resources when designing queries

Guides to using resources provided by the eProcurement Ontology to assist in constructing queries can be found https://docs.ted.europa.eu/docs-staging/epo-home/guide.html[here]. These are specific to EU public procurement and will help find the concepts or classes you will use in your queries.

== Procurement Data

Public procurement data available for query comes from notice data. For a short introduction of what data can be found in notices, you can go to the ted.europa.eu website and examine a notice. Any notice can be found by opening the latest issue of the Official Journal Supplement, or by using one of the several ways of searching for notices available on the site: advanced, expert, or browse by subject.

As an aid, you can use these short info sessions on xref:ROOT:attachment$/notice_data/index.html[Notice Data] and xref:attachment$searching_notices/index.html[Searching Notices] to familiarise yourself with notices and how to use the ted.europa.eu search possibilities.

This should give you a good idea of the information that can be found in a notice.