:doctitle: Query Central
:doccode: ods-main-prod-101
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: July 2024

Welcome to Query Central. Here you will find some SPARQL query examples suggested by the community collection.

If you are new to eProcurement and SPARQL Queries, you might want to read the xref:starting.adoc[Starting out with SPARQL Queries] page first.

In most cases we will examine a scenario in which a question about EU public procurement is asked. The following steps will be followed:

== Presentation of the scenario
* A short discussion of the the extent to which the current data offering can satisfy your question
* Understanding data limitations
* Refining the question

== Identifying the information to be returned
* Using the eProcurement ontology (glossary and conceptual model) to identify the classes and class relationships that can be used to find the information
* Constructing the query

== Executing the Query
* Running the Query
* Examining and refining the query results

In other cases we might try and help with syntax questions, or common difficulties with query construction. 

Community members are encouraged to discuss problems and help each other via GitHub Discussions.

== Query Examples

xref:query1.adoc[Query 1: xyz]