:doctitle: Tips when querying eProcurement data using SPARQL
:doccode: ods-main-prod-105
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: July 2024

=== Note

==== What data is available (from which notices and over what time period)?

Currently, the data available in Cellar is restricted to Contract Award Notices published between 1 September 2023 and 31 December 2023. #check dates#

==== Lots

All purchases are organised in into lots. Lots are effectively supply packages that enable supply to e.g., different locations, a subset of goods over time, etc. Even if only one delivery is stipulated, there is still a single lot. When querying, this can be confusing because it can look like data with the same notice number is duplicated in the results table, when actually it is showing rows of lots rather than the whole order in one row.

To clarify, you might want to add a column for lot number in your query.
 
==== Duplicate data in results

Apart from the appearance of duplication caused by lots, there are other reasons why there might be a duplication in the results. Notices could be published more than one language, so unless you filter this in the query, the same notice might be listed several times in different languages. #check accuracy and other reasons#

==== Availability of classes for querying

The project to develop the eProcurement Ontology is quite advanced, however it is not yet complete. There are still some modules that are in development. Therefore, data from earlier notices will not have been collected against classes that only came into existance in a later version of the ontology. It is important to bear this in mind when choosing classes for a query. You will need to check the relevant version of the ontology and going forward, possibly use more than one class in your query to cover all time periods.
