:doctitle: Data Available

== Data currently available

=== TED Linked Open Data
Data is currently available from August 2023 to December 2023

Notice Data is currently available from *Contract Award Notices* in the above time period +

NOTE: Linked open data is being constantly added to Cellar. Refer back to this page to check if there have been updates.

=== TED XML Schema Notice Data

The format of schema XML data has changed over the years in line with changes in the legislation. "Schema" refers to the fields required by law in the notice form and therefore to the data collected by the notice.

* Schema 2.08 applied to notices published before 2016, which was the year the 2014 directive on public procurement was applied.
* Schema 2.09 applied to notices published from 2016 until 1 February 2024 (non-EU Institutions) and 28 June 2024 (EU Institutions), when the transition period from schema 2.09 to eForms ended.
* eForms started on the 14 November 2022 and applies currently going forward. The transition period where two versions of notice data applied, schema 2.09 and eForms, was from the 22 November 2022 to the 28 June 2024.

NOTE: XML Schema Data is available from 1993 to the present day.

=== Notice types and when they are published in the public procurement process

When submitting a notice online, an electronic version of the standard forms set out in the the https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32019R1780[legislation] determines what data fields must be filled out in which type of form. It also mandates what type of data they contain, and whether the field is mandatory or optional. This is explained in detail on the legislation page and, although complex, the detail is useful in discovering which fields are available for query.

For an overview of what data can be extracted from a particular notice, you can also use the notice search facility available on the https://ted.europa.eu/en/[TED website]. Choose "Advanced Search" (All Notices), then the type of notice you are interested in, and then look at the contents of a notice from the list returned.

include::ROOT:partial$feedback.adoc[]