:doctitle: TED Open Data Service
:doccode: ODS-ROOT-004
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: September 2023

[.text-center]
= TED Open Data Service
:page-role: -toc

== What is the TED Open Data Service?

//[sidebar]
//--
The TED Open Data Service continuously converts notices from the XML standard form format available on the TED Website into RDF format. The data is stored in the Publications Office's (OP) triple store named the "Cellar", and is publicly available or "open". 

Making TED data open for querying is part of the https://digital-strategy.ec.europa.eu/en/policies/strategy-data[European Data Strategy] to connect EU data across sectors for the benefit of citizens, businesses, researchers, public administrations, and others.

//--


[.tile-container]
--

[.tile]
.How to query TED Open Data

****
Resources and links for querying TED Open Data

xref:querying:index.adoc[Query TED open data using SPARQL]
****

[.tile]
.Connect to the TED Open Data Service

****
Methods of connecting to TED Open Data

xref:connecting:index.adoc[Connect to TED open data]
****

[.tile]
.Example Query Library

****
Use or adapt the example SPARQL queries

xref:samples:index.adoc[Browse the sample queries provided]
****


--