= TED-SWS End-User Documentation

TED Semantic Web Service (TED-SWS) continuously converts public procurement notices from the XML format, available on the TED Website, into RDF format, and stores them in the CELLAR repository (database). From CELLAR, they can then be queried by the public through CELLAR’s SPARQL endpoint.

The TED-SWS makes information on public procurement notices accessible and reusable as Linked Open Data (LOD), by connecting to the data provided by data.europa.eu, which is a portal that makes many European datasets available to the general public for reuse. The rational for making public procurement notice data available can be found on the  xref:motivation.adoc[motivation page].


== Contents

[.tile-container]
--

[.tile]
.Mapping Suites
****
The TED-RDF Mappings are the transformation rules needed by the TED-RDF Conversion Pipeline (both of which are part of the TED Semantic Web Services, aka TED-SWS system) to convert TED notices available in XML format to RDF.

<<SWS:ROOT:mapping_suite/index.adoc#, Read the docs>>
****


[.tile]
.Sample Applications
****
Sample application represents a set of examples that shows how to interact with TED RDF Data (available in CELLAR) using tools like Python, R or Excel.

<<SWS:ROOT:sample_app/index.adoc#, Read the docs>>
****

--

////
== Audience

This documentation is written for a wide audience, with different interests in the TED-SWS project, and different levels of expertise Semantic Web, EU e-Procurement and software infrastructure. More specifically this documentation can be of interest to:

- *End-Users*, such as *Semantic Web Practitioners* or *Experts in eProcurement Domain*, who are interested in understanding how the RDF representation of the e-procurement notices look like, and how this representation conforms to the eProcurement Ontology (ePO).
- *Software Engineers* interested in integrating mapping suite packages into processing pipelines;
- *Semantic Engineers* interested in understanding and writing mappings from XML to RDF, in particular in the EU eProcurement domain;
////
