:doctitle: The TED Semantic Web Service Documentation
:doccode: sws-main-prod-001
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2023


== Introduction to the TED Semantic Web Service

The TED Semantic Web Service (TED-SWS) continuously converts Contract Award Notices from the xml standard form format available on the TED Website, into RDF format.  The RDF is stored in the Cellar repository, the semantic repository of the EU Publications Office. From there, the data can be queried from the https://publications.europa.eu/webapi/rdf/sparql[SPARQL end point on EU Vocabularies].

The following topics are included in this version of the Semantic Web Service Documentation:

== General Reference
* xref:audience.adoc[Target Audience] +
The target audience for this documentation

== Mapping Suite Contents

* xref:genref.adoc[Introduction] +
Introduction to the Mapping suites

* xref:glossary.adoc[Glossary] +
A glossary relating to the mapping suites
* xref:mapping_suite/methodology.adoc[Methodology] +
Describes the methodology for creating mapping rules
* xref:mapping_suite/repository-structure.adoc[Mapping Suite Repository Structure] +
Describes the repository structure for transformation rules and other artifacts
* xref:mapping_suite/index.adoc[Mapping suites] +
A description of the Mapping Suite contents
* xref:mapping_suite/mapping-suite-structure.adoc[Mapping suite Package Structure] +
A description of a mapping suite package structure
* xref:mapping_suite/code-list-resources.adoc[Code List Mappings] +
Resources used to map code lists in the XML files to URIs in the RDF representation
* xref:mapping_suite/preparing-test-data.adoc[Data samples] +
Describes TED notice data samples and methods used to generate them
* xref:mapping_suite/toolchain.adoc[Toolchain] +
Describes available CLI tools that can run on the mapping suites

== Reusing semantic web service artifacts

* xref:sample_app/sa_glossary.adoc[Glossary] +
A glossary relating to reusing semantic web service artefacts
* xref:sample_app/sparql_queries.adoc[Sparql Queries] +
Example queries run on the https://publications.europa.eu/webapi/rdf/sparql[sparql endpoint]
* xref:sample_app/ms_excel.adoc[MS Excel] +
Running queries using MS Excel macros
* xref:sample_app/jupyter_notebook_r.adoc[Jupyter Notebook - R] +
Running queries using Jupyter Notebook and R
* xref:sample_app/jupyter_notebook_python.adoc[Jupyter Notebook - Python] +
Running queries using Jupyter Notebook and Python



