:doctitle: The TED Open Data Web Service
:doccode: sws-main-prod-001
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2023


== Introduction to the Open Data Web Service

The TED Open Data Web Service continuously converts notices from the xml standard form format available on the TED Website, into RDF format.  The RDF is stored in the CELLAR repository. The data in CELLAR can be queried from the https://publications.europa.eu/webapi/rdf/sparql[SPARQL end point] on the EU Vocabularies. 

Currently, the service only converts contract award notices. It should be noted that contract award notices should not be confused with result notices in eForms.

This project falls clearly in the European data strategy which foresees a single market for data that will allow it to flow freely within the EU, and across sectors, for the benefit of businesses, researchers and public administrations.


The following topics are included in this version of the Open Data Web Service Documentation:

////
== Mapping Suites
A mapping suite within the TED Open Data Web Service is a set of mappings that defines how an XML document representing an e-Procurement Notice will be transformed to an equivalent RDF graph representation in conformance with the eProcurement ontology. These mappings are materialized in different forms, as it will be explained later, and a mapping suite will have all its relevant components organized in a package, which is referred to as a *mapping suite package*.A mapping suite can be further broken down into mapping suite packages, one per type of standard form mapped.
////



[.tile-container]
--

[.tile]
.Mapping Suites
****
The TED-RDF Mappings are the transformation rules needed by the TED-RDF Conversion Pipeline (both of which are part of the TED-SWS) to convert TED notices available in XML format to RDF.
Mapping Suites and Mapping Suite Packages are explained in this section.


<<SWS:ROOT:mapping_suite/index.adoc#, Read the docs>>
****


[.tile]
.Reusing Open Data Web Service artefacts
****
This section provides a set of examples that demonstrate how to extract TED RDF data from CELLAR using tools like Excel, Python, or R.

<<SWS:ROOT:sample_app/index.adoc#, Read the docs>>
****

--

////
== Audience

This documentation is written for a wide audience, with different interests in the TED-SWS project, and different levels of expertise Semantic Web, EU e-Procurement and software infrastructure. More specifically this documentation can be of interest to:

- *End-Users*, such as *Semantic Web Practitioners* or *Experts in eProcurement Domain*, who are interested in understanding how the RDF representation of the e-procurement notices look like, and how this representation conforms to the eProcurement Ontology (ePO).
- *Software Engineers* interested in integrating mapping suite packages into processing pipelines;
- *Semantic Engineers* interested in understanding and writing mappings from XML to RDF, in particular in the EU eProcurement domain;
////

