= TED-SWS End-User Documentation

TED Semantic Web Service (TED-SWS) is a pipeline system that continuously
converts the public procurement notices (in XML format) available on the
TED Website into RDF format based on the eProcurement Ontology, and publishes
them into CELLAR repository, hance making them available to the public
through CELLAR’s SPARQL endpoint.

The TED Semantic Web Service (TED-SWS) is plugging together
the TED infrastructure for the collection and publication of public procurement
notices with the infrastructure of http://data.europa.eu/[data.europa.eu]
in order to make public procurement data accessible and reusable as
Linked Open Data (LOD) by users and stakeholders (see xref:motivation.adoc[the detailed motivation]).

== Audience

This documentation is written for a wide audience, with different interests in the TED-SWS project, and different levels of expertise Semantic Web, EU e-Procurement and software infrastructure. More specifically this documentation can be of interest to:

- *End-Users*, such as *Semantic Web Practitioners* or *Experts in eProcurement Domain*, who are interested in understanding how the RDF representation of the e-procurement notices look like, and how this representation conforms to the eProcurement Ontology (ePO).
- *Software Engineers* interested in integrating mapping suite packages into processing pipelines;
- *Semantic Engineers* interested in understanding and writing mappings from XML to RDF, in particular in the EU eProcurement domain;

== Contents

[.tile-container]
--

[.tile]
.Mapping Suites
****
The TED-RDF Mappings are the transformation rules needed by the TED-RDF Conversion Pipeline (both of which are part of the TED Semantic Web Services, aka TED-SWS system) to convert TED notices available in XML format to RDF.

<<SWS:ROOT:mapping_suite/index.adoc#, Read the docs>>
****


[.tile]
.Sample applications
****
Sample application represents a set of examples that shows how to interact with TED RDF Data (available in CELLAR) using tools like Python, R or Excel.

<<SWS:ROOT:sample_app/index.adoc#, Read the docs>>
****

--
