:doctitle: The TED Open Data Service
:doccode: sws-main-prod-001
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2023


== Introduction

The TED Open Data Service continuously converts notices from the xml standard form format available on the TED Website, into RDF format.  The TED RDF data is stored in an RDF triple store named, "Cellar". The data in Cellar can be queried from Cellar's https://publications.europa.eu/webapi/rdf/sparql[SPARQL endpoint], linked to from the https://op.europa.eu/en/web/eu-vocabularies[EU Vocabularies page]. 

This project aligns with the goals of the https://digital-strategy.ec.europa.eu/en/policies/strategy-data[European Data Strategy] which aims to create a single market for data that allows data to flow freely within the EU, and across sectors, for the benefit of businesses, researchers, and public administrations.


The following topics are included in this version of the Open Data Service Documentation:

////
== Mapping Suites
A mapping suite within the TED Open Data Service is a set of mappings that defines how an XML document representing an e-Procurement Notice will be transformed to an equivalent RDF graph representation in conformance with the eProcurement ontology. These mappings are materialized in different forms, as it will be explained later, and a mapping suite will have all its relevant components organized in a package, which is referred to as a *mapping suite package*.A mapping suite can be further broken down into mapping suite packages, one per type of standard form mapped.
////



[.tile-container]
--

[.tile]
.Mapping Suites
****
The TED-RDF Mappings are the transformation rules needed by the TED-SWS Conversion Pipeline (both of which are part of the TED Open Data Service) to convert TED notices available in XML format into RDF.
Mapping Suites and Mapping Suite Packages are explained in this section.


<<ODS:ROOT:mapping_suite/index.adoc#, Read the docs>>
****


[.tile]
.Reusing TED Open Data
****
This section demonstrates how to query TED RDF data using Excel, Python, and R, and directly via the Cellar SPARQL EndPoint.

<<ODS:ROOT:sample_app/index.adoc#, Read the docs>>
****

--

////
== Audience

This documentation is written for a wide audience, with different interests in the TED-ODS project, and different levels of expertise Semantic Web, EU e-Procurement and software infrastructure. More specifically this documentation can be of interest to:

- *End-Users*, such as *Semantic Web Practitioners* or *Experts in eProcurement Domain*, who are interested in understanding how the RDF representation of the e-procurement notices look like, and how this representation conforms to the eProcurement Ontology (ePO).
- *Software Engineers* interested in integrating mapping suite packages into processing pipelines;
- *Semantic Engineers* interested in understanding and writing mappings from XML to RDF, in particular in the EU eProcurement domain;
////

