= The Motivation for the TED-Semantic Web Service

In General Objective 2 of its Strategic Plan for 2020-2024 , "A Europe fit for the digital age", the Publications Office identified three key requirements relating to data, “transparency and accountability, data quality, and the enhanced automation of data processing and interoperability”. It also identified a gap between the “wealth of open data, spread across multiple outlets, and the effort required to discover, access, and reuse it”.

The Strategic Plan for 2020-2024 commits to generating and sharing new knowledge as linked open data through an ecosystem of datasets, data models, ontologies and specialised services, accessible through a single entry point: http://data.europa.eu/[data.europa.eu], and following a "data-as-a-public-service" approach.

Current data is available in different xml formats which evolved historically in parallel, which make it difficult for users to consume and process data that span several years. The TED Semantic Web Service (TED-SWS) removes this barrier by providing one common format for accessing and reusing all TED data. Using the eProcurement Ontology, TED data will also have semantics attached to them allowing users to link them directly with other datasets. Users will also now be able to perform much more elaborate queries directly through the SPARQL endpoint. This will reduce their need for in-house data warehousing to perform complex queries.

A consistent format of data will enable a much larger number of use-cases, and an increased availability of analytics. The ability to perform complex queries on public procurement data will be open equally to both large information systems, and single users with a copy of Excel and an internet connection.

TED Semantic Web Service (TED-SWS) continuously converts the public procurement notices from the XML format, available on the TED Website, into RDF format, and stores them in the CELLAR repository. From CELLAR, they can then be queried by the public through CELLAR’s SPARQL endpoint.
