:doctitle: Mapping Suites
:doccode: sws-main-prod-010
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2023

== Introduction to mappings

A mapping suite within the TED Open Data Service is a set of mappings that define how an XML document representing an e-Procurement notice is transformed into an equivalent RDF graph representation that uses classes defined by the eProcurement ontology. These mappings correspond to the different forms, and the relevant components of a mapping suite are organised into a package known as a *mapping suite package*. A mapping suite can be broken down further into mapping suite packages, one per type of standard form mapped.

== Mapping Suite Contents
Transformation rules and other artefacts used for the mapping of Standard Forms and eForms for the TED Open Data Services (TED-ODS) system are organised in the ted-rdf-mapping repository.
The repository structure and folder descriptions are shown below.  The base of the folder path is https://github.com/OP-TED/ted-rdf-mapping/tree/main/  however if the reader wants to see a specific release, then the path is adapted by replacing main by the given release for example if release 2.1.1-rc.1 is required, the path will be https://github.com/OP-TED/ted-rdf-mapping/tree/2.1.1-rc.1

== Prior knowledge

It is assumed that the reader has a working knowledge of the following:

Semantic web technologies:: A good understanding of Semantic Web concepts and technologies is crucial. This includes knowledge of RDF triples, ontologies, and linked data principles.

RDF, RML and SPARQL:: Familiarity with RDF (Resource Description Framework) and the RML (the RDF Mapping Language) is important, while experience with SPARQL (SPARQL Protocol and RDF Query Language) is highly beneficial. TED-ODS provides data in RDF format and utilizes SPARQL for querying.

EU Procurement data and familiarity with the eProcurement Ontology:: If the goal is to understand how  mappings are used to transform specific types of EU procurement data, such as contract notices or award notices, it's important to have a basic understanding of these concepts, and the associated https://docs.ted.europa.eu/EPO/latest/index.html[eProcurement Ontology].

Familiarity with spreadsheet editing tools:: Since most of the conceptual mappings is done in a spreadsheet, working experience with spreadsheet editing tools such as MS Excel or Google Sheets, is beneficial.






//include::TED-ODS-introduction.adoc[Old Introduction]

//include::methodology.adoc[]

//include::toolchain.adoc[]

include::ROOT:partial$feedback.adoc[]