:doctitle: Mapping Suites
:doccode: sws-main-prod-010
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: October 2023

== Introduction to mappings

Description of how mapping works/ overview

== Prerequisites

To benefit thoroughly from the Mapping Suite Documentation, it is recommended that the reader have:

Knowledge of Semantic Web Technologies:: A good understanding of Semantic Web concepts and technologies is crucial. This includes knowledge of RDF triples, ontologies, and linked data principles.

Understanding of RDF, RML and SPARQL:: Familiarity with RDF (Resource Description Framework) and the RML (the RDF Mapping Language) is important, while experience with SPARQL (SPARQL Protocol and RDF Query Language) is highly beneficial. TED-ODS provides data in RDF format and utilizes SPARQL for querying.

Understanding of EU Procurement Data and Familiarity with ePO:: If your goal is to understand how the mappings are used to transform specific types of EU procurement data, such as contract notices or award notices, it's important to have a basic understanding of these concepts, and the associated https://docs.ted.europa.eu/EPO/latest/index.html[eProcurement Ontology].

Familiarity with Spreadsheet editing tools:: Since most of the Conceptual mappings is done in spreadsheet working experience with spreadsheet editing tools such as MS Excel or Google Sheets, is beneficial.



== Mapping Suite Contents
Transformation rules and other artefacts used for the mapping of Standard Forms and eForms  for the TED Open Data Services (TED-ODS) system are organised in the ted-rdf-mapping repository.
The repository structure and folder descriptions are shown below.  The base of the folder path is https://github.com/OP-TED/ted-rdf-mapping/tree/main/  however if the reader wants to see a specific release, then the path is adapted by replacing main by the given release for example if release 2.1.1-rc.1 is required, the path will be https://github.com/OP-TED/ted-rdf-mapping/tree/2.1.1-rc.1


=== Upper Level folders of the GitHub Repository

This section describes the upper level of the GitHub repository, the next section describes the lower levels of the GitHub repository where the more granular artefacts can be found. The aim of this section is to give the reader an overview of the repository structure.

[cols="1,1,2"]
|===
|Folder|Subfolders |Description

|/docs
|/antora
|Contains the documentation for the ted-rdf mapping

|https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings[/mappings]
a|https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03[/package_F03]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F06[/package_F06]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F13[/package_F13]
//https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F20[/package_F20]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F21[/package_F21]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F23[/package_F22]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F23[/package_F23]
https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F25[/package_F25]


NB: the example provided here is for Standard Form F03 but can be applied in the same way for the mapping suites for the other forms covered by the mappings.

a|Contains xref:mapping:mapping-suite-structure.adoc[mapping suite packages] organised based on the standard forms numbers. Their name is formed based on the form number (e.g. F03, F06) prefixed with package_ for readability. When the eForms are mapped, the corresponding appropriate organisation will be chosen.

| /mappings continued: subfolders
a|https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_2021[/package_F03/test_data/form_number_F03_2021]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_S01[/package_F03/test_data/form_number_F03_S01]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_S02[/package_F03/test_data/form_number_F03_S02]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_S03[/package_F03/test_data_form_number_F03_S03]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_S04[/package_F03/test_data_form_number_F03_S04]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/test_data/form_number_F03_S05[/package_F03/test_data_form_number_F03_S05]

NB the example provided here is for Standard Form F03 but can be applied in the same way to the other form package.

a|Contains example notices extracted from the TED website with real data for the forms concerned in this example F03.

The folder ending F03_2021 contain examples from notices published in 2021

The folder ending F03_S01 contains examples from notices published using the xml release R2.0.9.S01.E01

The folder ending F03_S02 contains examples from notices published using the xml release R2.0.9.S02.E01, and so forth whereby the S01 is replaced by either S02, S03, S04 and S05


The latest publication xml can be found at TED schemas - EU Vocabularies - Publications Office of the EU (europa.eu) under Publication Schema the Excel file in the zip file provides the change log between schema.



|https://github.com/OP-TED/ted-rdf-mapping/tree/main/src[/src]
a|https://github.com/OP-TED/ted-rdf-mapping/tree/main/src/mappings[/mappings]

a|Contains the "single source of truth" for the mapping rules across various mapping suite packages. This is necessary because of the modularisation and reuse method adopted in this project. The basic idea is that the mapping rules are organised in modules, and all are stored in the source folder.

Each mapping suite provides in the conceptual mapping workbook the list of modules that be used to compose the complete set of transformation rules of the mapped form number.

|/test_data
a|https://github.com/OP-TED/ted-rdf-mapping/tree/main/test_data/sampling_2014_2022[/sampling_2014_2022]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/test_data/sampling_2021[/sampling_2021]

https://github.com/OP-TED/ted-rdf-mapping/tree/main/test_data/sampling_manual/form_number_F03[/sampling_manual]
a|Covers samples of notices across all form types whether they are covered by the actual mappings covered to date.

The samples are broken down by a mapping to the eForms sub-type:

/sampling_2014_2022 and sampling_2021 cover notices over the respective periods and are generated respectively.

/sample_manual are notices that have been produced manually concerning F03

Test data is also provided in the mapping suite packages that are specific to the mapping suites.

|===


=== The lower level folders of the GitHub Repository

This section provides more detailed information on the content available in the lower levels of the repository:

* Mapping suite package structure

** output

** test-data

** transformation

** validation

* source files

** mappings

** validation



//include::TED-ODS-introduction.adoc[Old Introduction]

//include::methodology.adoc[]

//include::toolchain.adoc[]

include::ROOT:partial$feedback.adoc[]