= Querying the data using Excel

There are two parts to querying the data using Excel. 

== Part 1 of this query method

The first part is described on the page: xref:sparql.adoc[Submitting a query in the Cellar SPARQL Endpoint].

video::P9IgUoJ3L60[youtube, width=720, height=540]

NOTE: When submitting your query, be sure that you choose the first results format option in the dropdown list, *HTML*.


== Part 2 of this query method

Once the EndPoint has returned the results of the query:

. Copy the url of the results page to the clipboard
. Open a new spreadsheet in Microsoft Excel
. Go to the *Data* tab and choose "from Web" on the Data menu
. Paste the copied query results into the window that pops up and click "OK". A new window will appear requiring you to choose the sheet you wish to look at. The sheet you want is the generated one, "Table x" (x will be a number: 0, 1, etc.The table number might be different in your application)
. Choose "Table x" and click on either "Load", or "Transform Data". 
* "Load" will copy all columns as is into the Excel sheet. 
* "Transform Data" will open a Power Query window that will allow you to delete the columns you do not wish to keep and to do some manipulation of the data before it is transferred to the Excel sheet. Click "Close and Load" when you are finished.
. This will save your settings and return you to the new Excel sheet. Here you can rename the table and perform further data manipulation, create charts, etc.

If you save this query in Excel, the data will be refreshed the net time you open the file. You can also refresh the data anytime by clicking on "Refresh" on the *Data* menu.

video::G_7cCGQaICY[youtube, width=720, height=540]

include::ROOT:partial$feedback.adoc[]