= Connecting to the data

== Running a query

RDF databases or triple stores provide a URI or EndPoint into which a data reuser can submit a query, and receive their results. It looks a little like a web address for searching, except that it queries the specific triple store to which it is attached. There are a few EndPoint interface applications that RDF triple store managers can adopt and Cellar uses the Virtuoso EndPoint application.

=== Querying directly via the Cellar SPARQL EndPoint

If you are new to querying RDF data, you can start by pasting a sample query directly into the SPARQL Endpoint. You can view the results online and/ or download them in a variety of formats.

xref:connecting:sparql.adoc[How to query directly via the Cellar SPARQL EndPoint]

=== Querying using Microsoft Excel

Use Microsoft Excel to create a file with a permanent link to your query and update the data from within Excel whenever you wish. You can also use Excel to create charts, graphs and other visual representations of the data easily.

xref:connecting:excel.adoc[How to query using Microsoft Excel]


=== Querying using Jupyter Notebooks and Python

Technical users can connect to the data using Jupyter Notebook and Python

xref:connecting:python.adoc[How to query using a Jupiter Notebook and Python]

Connect to the data using a sample Jupyter Notebook and Pandas Dataframes online via a Google Colaboratory space

Use the resources and sample queries to try out these methods to see which suits you best.

include::ROOT:partial$feedback.adoc[]